### ISSUE TITLE
ArgInOut

### ISSUE THREAD

**Issue by yaqiz01** [raghup17/plasticine#20]
I’m still on ArgInOut. It seems there’s some problem at scalarInXbar
![screenshot 2016-11-14 22 30 16](https://cloud.githubusercontent.com/assets/5553709/20296497/14849f6a-aac0-11e6-8918-b9bb7d1d7d69.png)
You can see I set databus to be 12 - 27, and I set scalarInXbar to be
"outSelect" : ["x","x","x","3","x","x","x","x"]
But the cross Bar input seems to be off

**Comment by raghup17** [comment]
Seems like the config is picking input3 for output3, which is reflected in the xbar debug output.

**Comment by raghup17** [comment]
Closing old issue that isn't relevant now.
