### ISSUE TITLE
Control Block

### ISSUE THREAD

**Issue by yaqiz01** [raghup17/plasticine#5]
Is the TokenOut cross bar before or after enable mux?

Or does it make sense just merge the enable mux into the TokenOut cross bar? Something like
<img width="1108" alt="controlblock_pdf__1_page__and_evernote_basic" src="https://cloud.githubusercontent.com/assets/5553709/19103230/3fce3c3a-8b08-11e6-8a78-91d2e9184e0b.png">

@raghup17

**Comment by raghup17** [comment]
Timing and area:
If we replace the existing muxes with a crossbar, that would mean that we have four 8:1 muxes to drive each of the four token outs.

On the other hand, if the crossbar is after the existing muxes, that would require 4 2:1 muxes + 4 4:1 muxes. (111.48, 327.36, delay = 0.0497). From the characterization data, this seems to be 32% smaller in area, but with 13% higher delay. Both require same amount of config bits. 

Given that the crossbar offers greater flexibility, and is actually faster at the expense of a little more area, I am inclined to put a crossbar (like you have indicated in the blue) and get rid of the existing muxes.

**Comment by blackwings-01** [comment]
I prefer a cross bar there as well

**Comment by raghup17** [comment]
Problem solved! We can get rid of those mux configs and call it a "tokenOutXbar" in PISA for now. I will change the control block accordingly.

**Comment by blackwings-01** [comment]
Additional Tokenin crossbar

<img width="1108" alt="controlblock_pdf__1_page__and_evernote_basic" src="https://cloud.githubusercontent.com/assets/5553709/19413329/d15d4988-92de-11e6-8ecc-07716df76c81.png">

**Comment by blackwings-01** [comment]
Adding FIFONotFull and FIFOAndTree
<img width="1108" alt="controlblock_pdf__1_page__and_evernote_basic" src="https://cloud.githubusercontent.com/assets/5553709/20025808/73ade190-a2af-11e6-97d5-5686d7906a6f.png">
@raghup17 
What's the name of the mux attached to TokenDown Pulser?
At the moment it's generated as
```
              "tokenDownLUT": [
                {
                  "table" : "x",
                  "mux" : "x"
                },
                {
                  "table" : "x",
                  "mux" : "x"
                }
           }
```

**Comment by raghup17** [comment]
syncTokenMux. The modified single CU dotproduct PISA contains an example on how this is used.

**Comment by raghup17** [comment]
Good suggestion, we can add those muxes to handle FIFO tokenOuts. 
We can call the muxes 'fifoEnableMuxes'. The config can be:
'0' / 'x' : Pick the up-down counter value
'1' : Pick FIFO tree value

Example in PISA:
`"fifoEnableMuxes" : [ "x", "x", "1", "x"]`

The ordering in the array is numbered top (0) to bottom (numCounters-1) in the picture.

I am making all these changes to the ControlBox tonight, I will send a new picture for now :-).
We can move all drawings to draw.io post deadline.
