### ISSUE TITLE
Memory Controller Control Interface

### ISSUE THREAD

**Issue by yaqiz01** [raghup17/plasticine#8]
![blank](https://cloud.githubusercontent.com/assets/5553709/20025960/8724949c-a2b1-11e6-9d68-ecf7a90634f7.png)

For tile load this is what generated by spatial at the moment. There're a couple awkward issues here.
1. The memory controller MC is really a nested MetaPipe { StreamController {StreamPipeline}}, which I would assume it internally contains these controllers. One issue is that tokenIn from UnitPipe would be a pulse because UnitPipe and MC are MetaPipe relationship, but "issue" command to memory controller is a steady signal. The enqueue signal from MC ("done") to the FIFOOnWrite (writing side is FIFO, reading side is SRAM) needs to be a steady signal, but "tokenOut" of a MetaPipeline needs to be a pulse

2. And by convention, the outer controller would lives in the last stage, so MetaPipe2 would live in MC, and I should chain MC's CounterChain with MetaPipe2's CounterChain, however I don't have access to MC's CounterChain

A solution that might works is to add a control block to the memory controller (which can be a much smaller size than normal control block) with a spatial fake counter ("MC" counter), where
(a) the MC counter enable is connected to issue command of the memory controller. This way I can route tokenIn (pulse) from the UnitPipe at tokenIn of the control block, and allocate a tokenBuffer, which drives enableLut/enable of the "MC" counter, a steady signal, which is both the issue command and the FIFO enqueue signal at Pipe1.
(b) the done of the MC counter is not result of counting to max, but rather connected to actual done signal of the memory controller. This way, I can chain the done of the MC counter with outer MetaPipe2's counter, and generated the tokenOut from MC to UnitPipe (not MetaPipe2.done && MCCounter'done), and tokenOut from MetaPipe2 to Pipe1, (MetaPipe2.done)

<img width="1463" alt="mc_control_box" src="https://cloud.githubusercontent.com/assets/5553709/20026834/40243aca-a2c0-11e6-8672-5feabbdcc091.png">

**Comment by raghup17** [comment]
Ah. Interesting. A few issues and clarifications:

1. Starting MetaPipe2: One clarification here. In our convention, we have assumed that the 'start' token comes to the last stage of a MetaPipe, from where it gets sent to the first stage. Does this mean that the tokenIn for MetaPipe2 first comes to the MC, from where it goes to the UnitPipe? The MC currently doesn't support that, but it can easily be added.

2. token from UnitPipe -> MC (or MC issue): The issue signal is a pulse. It acts as a 'enqValid' for the FIFOs within the MC. Given that a unit pipe can issue only a single command at a time, using its tokenOut directly should be fine.

3. enqValid from MC -> Pipe1: Routing the MC's counter enable would be a bit dangerous as we don't know how long data would take to come back from DRAM. The MC currently generates a 'valid' for every burst of data when it comes back. This signal can be routed to Pipe1 and used as 'enqValid'. 

4. MetaPipe2 'done': The organization in your picture suggests that the second iteration of Metapipe1 cannot begin until after Metapipe2 finishes, or the MC completes the current request. Is this organization how it is? I thought it was: 
```
MetaPipe1(N by row) {
    UnitPipe
    MC
    Pipe1
}
```
I know we talked about this before, but what's the issue in calling MetaPipe1 a stream controller, and using the 'N by row' counter as the stream counter? If Pipe1 is just doing FIFO writes, the only counter in the three stages is the stream counter. This also allows abstracting the memory controller as a streaming stage with a bunch of input FIFOs (address, data if store), that produces an output into a FIFO.

**Comment by blackwings-01** [comment]
1. Correct, this the MetaPipe.tokenDown in at tokenIn in the control box picture and TokenDown to UnitPipe at tokenOut in the control box
2. The purpose of adding this control box here is to allow converting the pulse TokenIn to a steady signal "issue" at enable of MC counter, and allowing MetaPipe2 to live in MC by our convention. 
3. I think you are right here
4. The first picture's organization is
```
MetaPipe1(N by row) {
  MetaPipe2(1 by 1) {
    UnitPipe()
    MC
  }
  Pipe1
}
```
So MetaPipe1 cannot be a StreamController because MetaPipe2 is a MetaPipeline. And UnitPipe happens

**Comment by raghup17** [comment]
// 2-d load
MetaPipe1(N by rowBlockSize) {  i =>
  MetaPipe2(rowBlockSize) {  r =>
    UnitPipe()  // Issue cmd to load row (r+i)
    MC
    Pipe   // The thing that gets optimized away
  }
  Pipe1 (row by 1)
}

**Comment by blackwings-01** [comment]
For
<img width="1399" alt="mc_control_box" src="https://cloud.githubusercontent.com/assets/5553709/20028047/de72f306-a2e3-11e6-9495-aa439cb2b589.png">
 reference

**Comment by blackwings-01** [comment]
If we model memory controller with proper streaming control, does that mean there will no longer be `MC.issue` signal. Instead I'm modeling the address and data FIFO. So for tileLoad I will have access to `MC.addrEnq` and for TileStore I have access to both `MC.addrEnq` and `MC.dataEnq`. The major difference is that `MC.addrEnq ` and `MC.dataEnq ` are step signals now rather than a pulse. 
<img width="782" alt="screenshot 2016-11-12 09 04 44" src="https://cloud.githubusercontent.com/assets/5553709/20239537/26c9b846-a8b7-11e6-8516-15b6a756e97c.png">

**Comment by raghup17** [comment]
That's right. Quick clarification on `MC.done` (I'm adding that to the MC right now):
This signal is derived from an internal counter's 'done', as you mentioned. The only purpose this is serving is to update the outer controller when it is done. I could internally chain the `MC.done` counter with the first counter in the counter chain. In other words, the innermost (0th) counter will be hardwired to be enabled by `MC.done` internally.

From your side, you will allocate counters for the outer controllers in the counter chain within MC. So MC.done will be transparent to you. Does this work?

**Comment by blackwings-01** [comment]
Yeah that works
